name: development CI

on: [push, pull_request]

jobs:
  dev_CI:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm install
        run: npm install
        
      - name: Prettier Action
        run: npm run format

      - name: ESLint Action eslintrc
        run: npm run lint
                
      - name: npm run test
        run:  npm run test:e2e
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
